cartouche_cartouche:
    resource: "@CartoucheCartoucheBundle/Controller/"
    type:     annotation
    prefix:   /

cartouche_front:
    resource: "@CartoucheFrontBundle/Controller/"
    type:     annotation
    prefix:   /

