cartouche_cartouche:
    resource: "@CartoucheCartoucheBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CartoucheFrontBundle:Front:index.html.twig'
        maxAge: 604800
        sharedMaxAge: 604800
        private: false
