<?php

namespace Cartouche\CartoucheBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartoucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartoucheRepository extends EntityRepository
{
}
